create table quantities (id bigint generated by default as identity, next_id bigint, previous_id bigint, quantity float8, reason_for_a_change varchar(255), product_id bigint,
 primary key (id));
alter table if exists quantities add constraint FK_quantities_products foreign key (product_id) references products;