create table baskets (id bigint generated by default as identity, quantity double precision, product_id bigint, user_id bigint,
 order_id bigint, creation_date TIMESTAMP WITHOUT TIME ZONE, primary key (id));
alter table if exists baskets add constraint FK_basket_products foreign key (product_id) references products;
alter table if exists baskets add constraint FK_basket_users foreign key (user_id) references users;