create table distributors (name varchar(255), id bigint not null, primary key (id));
create table user_connections (id bigint generated by default as identity, detail_connection varchar(255), type_connection varchar(255), user_id bigint, primary key (id));
create table user_role (user_id bigint not null, user_roles varchar(255));
create table users (id bigint not null, active boolean, login varchar(255), password varchar(100), primary key (id));
alter table if exists users drop constraint if exists UK_login;
alter table if exists users add constraint UK_login unique (login);
alter table if exists distributors add constraint FK_distributors_users foreign key (id) references users;
alter table if exists user_connections add constraint FK_user_connections_users foreign key (user_id) references users;
alter table if exists user_role add constraint FK_user_role_users foreign key (user_id) references users;