create table product_categories (id bigint generated by default as identity, name varchar(255) not null,
 descriptrion varchar(255), createdDate date,
 lastUpdatedDate date, active bool, primary key (id));
create table product_sub_categories (id bigint generated by default as identity,
 name varchar(255) not null, active bool, product_category_id bigint, primary key (id));
alter table if exists product_categories add constraint UK_name_product_categories  unique (name);
alter table if exists product_sub_categories add constraint UK_name_product_sub_categories unique (name);
ALTER TABLE product_sub_categories ADD CONSTRAINT FK_product_categories_product_sub_categories
FOREIGN KEY (product_category_id) REFERENCES product_categories (id);