CREATE TABLE product_price ();
ALTER TABLE product_price ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;
ALTER TABLE product_price ADD price money;
ALTER TABLE product_price ADD created_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE product_price ADD last_updated_date TIMESTAMP WITHOUT TIME ZONE;
alter table product_price ADD active bool;
alter table if exists product_price add column product_id bigint;
alter table if exists product_price add constraint FK_product_price_product foreign key (product_id) references products;